### PR TITLE
add performance metrics for FederatedHPA

### PR DESCRIPTION
**Pull request by zhy76**
**What type of PR is this?**

**What this PR does / why we need it**:
add performance metrics for FederatedHPA
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by zhy76** [comment]
cc @jwcesign

**Comment by RainbowMango** [comment]
Do we need to update the [zh docs](https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/metrics.md) in this PR or follow up?

**Comment by jwcesign** [comment]
Hi, @zhy76 , could you assist in updating https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/metrics.md as well?

**Comment by zhy76** [comment]
> Hi, @zhy76 , could you assist in updating https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/metrics.md as well?

Sure~

**Review by RainbowMango — APPROVED** [review]
/approve

Leave LGTM to @jwcesign 

Thanks, I see you added missing `cronfederatedhpa_rule_process_duration_seconds` too.

**Pull request merged**
