### PR TITLE
docs: add pod to InterpretReplica support list

### LINKED ISSUE #451: Update Pod to the default InterpretReplica support list
**What would you like to be added**:

As https://github.com/karmada-io/karmada/pull/3876, we need to update the site: https://karmada.io/docs/next/userguide/globalview/customizing-resource-interpreter/#interpretreplica

**Why is this needed**:

/help

### PR DESCRIPTION
**Pull request by rakshitgondwal**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
Changes made:
- Added `Pod(v1)` to the InterpretReplica support list in https://karmada.io/docs/next/userguide/globalview/customizing-resource-interpreter/#interpretreplica

**Which issue(s) this PR fixes**:
Fixes #451

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
@rakshitgondwal Thanks, can you help make some changes to this file at the same time?
```
i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
```

**Comment by rakshitgondwal** [comment]
Hi @XiShanYongYe-Chang, please check.

**Comment by XiShanYongYe-Chang** [comment]
Hi @rakshitgondwal, can you help squash your commits into one?

**Comment by rakshitgondwal** [comment]
Done, please check @XiShanYongYe-Chang

**Comment by rakshitgondwal** [comment]
Thank you for the merge!

**Pull request merged**
