### PR TITLE
fix hero area on tablet

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/karmada-io/website/issues/15

### CODE REVIEW

**Comment by RainbowMango** [comment]
Hi @chinmaym07, can you help take a look at this?

**Comment by chinmaym07** [comment]
Hey @Arhell. 
First of thanks for pointing & solving the issue . Great work on this. 🚀 .

Two More improvements are there.
1. Please increase the space between hero & the navbar below `992px`
2. Please add the overflow property to body as the body overflows horizontally when in mobile view.

You can verify the improvements here as why they are required here.

https://user-images.githubusercontent.com/44670961/158697145-9fcc9199-fd5b-41db-8379-7692fe441c01.mp4


There are some more issues which are not linked to this section . Separate issues can be created for them & can be tracked from there.

**Comment by Arhell** [comment]
@chinmaym07 done

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Good job! Thank you guys @chinmaym07 @Arhell

**Pull request merged**
