### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/karmada-io/website/issues/303

### CODE REVIEW

**Comment by RainbowMango** [comment]
Hi @Arhell Can you give a link to the release note of v2.3.1? And is there anything we need to know about the change?

**Review by Arhell — COMMENTED** [review]
https://github.com/facebook/docusaurus/blob/main/CHANGELOG.md#231-2023-02-03

**Comment by RainbowMango** [comment]
/lgtm
/approve
Thanks.

**Pull request merged**
