### PR TITLE
Add blog `karmada-v1.3`

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please add https://docusaurus.io/docs/blog#adding-posts

`<!--truncate-->`

the whole post will not be displayed on the main page

for example somewhere here after the post
https://github.com/karmada-io/website/pull/161/files#diff-01e3dcc98f0764bd5074f0b29f971383072a918e1250d2313ba1b4666f21e869R15

**Comment by XiShanYongYe-Chang** [comment]
Hi @Arhell, thanks for your guidance.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
