### PR TITLE
Add SINA to Karmada Adopters

### PR DESCRIPTION
**Pull request by xudongyang95**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by RainbowMango** [comment]
Thanks @xudongyang95 for your support, that means a lot to the community!

Could you please help to sign the commit to make CI happy:), you can do that according to the guideline:
https://github.com/karmada-io/website/pull/398/checks?check_run_id=14553414524

or, just run following commands:
``` 
# git checkout main
# git rebase HEAD~1 --signoff
# git push --force-with-lease origin main
```

**Comment by SAMZONG** [comment]
/lgtm

Thank you very much for choosing Karmada!

**Review by RainbowMango — APPROVED** [review]
/approve

Thanks again! Appreciate your support.

cc @Poor12

**Comment by Poor12** [comment]
Thank you very much for choosing Karmada!

**Pull request merged**
