### PR TITLE
fix typos error of documents

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

fix typos error of documents

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Did #552 only fix part of all typos?

**Comment by chaosi-zju** [comment]
> Did #552 only fix part of all typos?

yes, this is the last part, and I will submit the CI auto check tool in next PR~

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
> yes, this is the last part, and I will submit the CI auto check tool in next PR~

I don't quite understand what's the last, though.

**Comment by chaosi-zju** [comment]
> I don't quite understand what's the last, though.

the tool has reported so many typo errors, and I fixed it  in batches, just like:

image

`last` means after this PR merged, the errors reported by this CI tool would all been fixed, just like:

image

**Pull request merged**
