### PR TITLE
fix hero logotype

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/karmada-io/website/issues/43

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @rgrupesh 
Could you please help with it?

**Comment by RainbowMango** [comment]
Looks good to me from the preview.
@rgrupesh I'm going to move this forward, If you have other comments, please file a PR for it.

**Comment by rgrupesh** [comment]
@RainbowMango logo LGTM as well. But it seems, `how it works` is deformed

### Screenshot
Screenshot from 2022-05-09 08-06-27

**Pull request merged**
