### PR TITLE
[zh]translate docs: global-search-for-resources.md

### PR DESCRIPTION
**Pull request by huan555**
Add one of the following kinds:

/kind documentation

### CODE REVIEW

**Comment by windsonsea** [comment]
Please run the following commands to add your signature:

```
git commit -s --amend
git push origin wh01 -f
```

**Review by windsonsea — COMMENTED** [review]
This file has been included in #412. You need to perform the rebase.
···
i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/globalview/aggregated-api-endpoint.md
···

**Comment by huan555** [comment]
> git push origin wh02 -f

I have run the command, thx

**Comment by windsonsea** [comment]
No, still not correct.

**Pull request closed without merging**
