### PR TITLE
Add note for mcs document: kubernetes version and pod/service CIDRs

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

As talk in https://github.com/karmada-io/karmada/issues/2460#issuecomment-1238836360 and https://github.com/karmada-io/karmada/issues/2657, we need to add some notes to help users better experience the MCS feature.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

/cc @631068264

### CODE REVIEW

**Comment by RainbowMango** [comment]
@631068264 would you like to take a look it?

**Comment by 631068264** [comment]
@RainbowMango @XiShanYongYe-Chang 

我觉得应该把这些提示**提前**一点说明，例如安装karmada之前就应该提示，**因为这涉及到CIDR规划和集群版本，后期修改升级的操作会给运维带来非常大麻烦。**

如果等到用户翻到MCS的文档或者突然想用MCI的时候才知道，就有点滞后。除非karmada有方便没有副作用的补救措施。

根据 https://github.com/karmada-io/karmada/issues/2460#issuecomment-1237811975 核心问题是MCI使用EndpointSlice，只不过MCS依赖MCI，也就是说MCI部分就已经有问题。

**Comment by XiShanYongYe-Chang** [comment]
Hi @631068264, 这个修改可以继续推进么？

**Comment by 631068264** [comment]
> Member

可以

**Comment by XiShanYongYe-Chang** [comment]
> > Member
> 
> 可以

好的，多谢~

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
