### PR TITLE
remove mui/material

### PR DESCRIPTION
**Pull request by Arhell**
**What type of PR is this?**
use docusaurus styles

/kind cleanup

**Which issue(s) this PR fixes**:
resolve https://github.com/karmada-io/website/issues/84

### CODE REVIEW

**Comment by Arhell** [comment]
/assign @RainbowMango
/assign @rgrupesh
removed an optional package that was only in the 1st section

**Comment by Arhell** [comment]
> /assign @RainbowMango /assign @rgrupesh removed an optional package that was only in the 1st section
and will build a little faster

**Comment by Arhell** [comment]
@RainbowMango
@rgrupesh

**Comment by Arhell** [comment]
cc @RainbowMango @rgrupesh

**Comment by RainbowMango** [comment]
/assign @pigletfly @rgrupesh 
Could you please help to take a look?

**Pull request closed without merging**
