### PR TITLE
Add neen to adopters

### PR DESCRIPTION
**Pull request by djcenox**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by rgrupesh — COMMENTED** [review]
@djcenox I can't see your changes yet. 

https://deploy-preview-280--karmada.netlify.app/docs/casestudies/adopters/

Can you please abide by the markdown format and push your changes again?

**Review by djcenox — COMMENTED** [review]
fix spaces

**Review by djcenox — COMMENTED** [review]
nothin

**Comment by djcenox** [comment]
it's working in my repo https://github.com/djcenox/website/blob/main/docs/casestudies/adopters.md

So I don't understand why not in netlify

**Comment by Poor12** [comment]
Thanks for contribution! I have seen the changes in the `Next` view. Could you sign the DCO here https://github.com/karmada-io/website/pull/280/checks?check_run_id=10277259558?

**Comment by RainbowMango** [comment]
Here is the preview: https://deploy-preview-280--karmada.netlify.app/docs/next/casestudies/adopters

It works well.

**Review by rgrupesh — COMMENTED** [review]
Looks good now. Just squash the commit and it's done.

**Comment by RainbowMango** [comment]
@djcenox Thanks a ton!
Could you please sign your commit? And here is the guide line:
https://github.com/karmada-io/website/pull/280/checks?check_run_id=10277259558

**Pull request closed without merging**
