### PR TITLE
Give more clear steps about how to install karmada with binaries

### PR DESCRIPTION
**Pull request by jwcesign**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
none

**Which issue(s) this PR fixes**:
Fixes #none

**Special notes for your reviewer**:
none

### CODE REVIEW

**Comment by jwcesign** [comment]
cc @XiShanYongYe-Chang @Poor12

**Comment by jwcesign** [comment]
cc @RainbowMango

**Comment by XiShanYongYe-Chang** [comment]
Hi @cmicat, can you help take a review?
/cc @cmicat

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
