### PR TITLE
updaete blog title

### PR DESCRIPTION
**Pull request by fengshunli**

### CODE REVIEW

**Comment by RainbowMango** [comment]
I prefer to remove this document, how do you say? @Poor12 

This document high light the features of v1.3, a little bit outdated now.

**Comment by Poor12** [comment]
> I prefer to remove this document, how do you say? @Poor12
> 
> This document high light the features of v1.3, a little bit outdated now.

I think the key question is whether we need to maintain and update the blog content for a long time.  Blogs are updated less frequently and with less content now.

**Comment by RainbowMango** [comment]
So, what's your opinion?

**Comment by fengshunli** [comment]
> I prefer to remove this document, how do you say? @Poor12
> 
> This document high light the features of v1.3, a little bit outdated now.

how to deal with this @RainbowMango

**Comment by Poor12** [comment]
I think it'ok to delete. But we should decide a time point to update the blog.

**Comment by fengshunli** [comment]
Is it okay to follow my translation?

**Comment by RainbowMango** [comment]
Let's remove this document instead of translating it.

**Comment by fengshunli** [comment]
> Let's remove this document instead of translating it.

delete blog this document mom

**Comment by RainbowMango** [comment]
fine. let's move forward for now.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by fengshunli** [comment]
> fine. let's move forward for now.

ok

**Pull request merged**
