### PR TITLE
Rename partner name of unionbigdata

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
This PR updates the partner name as per https://github.com/karmada-io/website/pull/531#discussion_r1448230342

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @pandaoknight 
You can see the preview at:
- Engish: https://deploy-preview-549--karmada.netlify.app/partners/
- Chinese: https://deploy-preview-549--karmada.netlify.app/zh/partners/

**Review by Arhell — COMMENTED** [review]
/lgtm

**Review by windsonsea — APPROVED** [review]

**Review by XiShanYongYe-Chang — COMMENTED** [review]
LGTM

**Comment by pandaoknight** [comment]
Thanks, it looks good to me :)

**Comment by RainbowMango** [comment]
Thanks for the confirmation.

**Pull request merged**
