### PR TITLE
Update working-with-velero.md

### PR DESCRIPTION
**Pull request by SAMZONG**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes Head style error

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by Poor12** [comment]
Could you please sync the changes into `current` directory?

**Comment by SAMZONG** [comment]
> Could you please sync the changes into `current` directory?

Ok, I'm done

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
