### PR TITLE
[doc] optimize text and layout of core-concept.md

### PR DESCRIPTION
**Pull request by windsonsea**
The original webpage is https://karmada.io/docs/getting-started/core-concept

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Have a try to make it beautiful and official. 

**Which issue(s) this PR fixes**:
Grammar and layout optimization

**Special notes for your reviewer**:
Not sure if all my changes are correct or not. Need your confirmation, thanks.
@rgrupesh @Arhell

### CODE REVIEW

**Comment by RainbowMango** [comment]
Thanks @windsonsea 
Please @rgrupesh @Arhell help.

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by RainbowMango** [comment]
@windsonsea Thanks.

**Pull request merged**
