### PR TITLE
[zh]modify docs format

### PR DESCRIPTION
**Pull request by justedennnnn**
Signed-off-by:  justedennnnn  chenlu.li@daocloud.io

**What type of PR is this?**

**What this PR does / why we need it**:
modify docs format

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by SAMZONG — CHANGES_REQUESTED** [review]
Good! Can you modify English version?

```bash
./docs/key-features/features.md
```

**Comment by justedennnnn** [comment]
> Good! Can you modify English version?
> 
> ```shell
> ./docs/key-features/features.md
> ```
ok

**Comment by SAMZONG** [comment]
/lgtm
/approve

Thanks.

**Comment by SAMZONG** [comment]
@RainbowMango Take a look, when you have time

**Review by RainbowMango — APPROVED** [review]
/approve

Thanks!

**Pull request merged**
