### PR TITLE
refactor: use docusaurus for docs and blog

### PR DESCRIPTION
**Pull request by pigletfly**
Signed-off-by: pigletfly <wangbing.adam@gmail.com>

### CODE REVIEW

**Comment by RainbowMango** [comment]
The preview is broken? 
https://deploy-preview-31--karmada.netlify.app/

**Comment by pigletfly** [comment]
> The preview is broken? https://deploy-preview-31--karmada.netlify.app/

because we are using docusaurus instead of hugo, so the configuration on netlify should be changed as well,such as build method

**Comment by pigletfly** [comment]
or we can merge this PR to a separate branch, then tune netlify config on this branch

**Comment by RainbowMango** [comment]
> or we can merge this PR to a separate branch, then tune netlify config on this branch

That's a good idea, but hold on for a while. I'll see how to config the netlify.

**Comment by RainbowMango** [comment]
According to [Deploying to Netlify](https://docusaurus.io/docs/deployment#deploying-to-netlify), I set:
- build command: npm run build
- `base`~build~ directory: build  （Note: the document might be outdated, there is no `build directory` anymore）

Is that right? Can you help push again to re-trigger the build?

**Comment by rgrupesh** [comment]
> or we can merge this PR to a separate branch, then tune netlify config on this branch



> According to [Deploying to Netlify](https://docusaurus.io/docs/deployment#deploying-to-netlify), I set:
> 
> * build command: npm run build
> * `base`~build~ directory: build  （Note: the document might be outdated, there is no `build directory` anymore）
> 
> Is that right? Can you help push again to re-trigger the build?

Try pushing now @pigletfly. If still doesn't work, we can try merging this PR into separate branch(as you stated earlier) and preview using that.

**Comment by adithyaakrishna** [comment]
@RainbowMango The build runs successfully if we use yarn 👀

**Comment by pigletfly** [comment]
> @RainbowMango The build runs successfully if we use yarn 👀 I guess @pigletfly used yarn while refactoring and thus there is no package-lock.json file

yes, we using yarn to install depends and build. @RainbowMango can you change `npm run build` to `yarn run build` ?

**Comment by RainbowMango** [comment]
>  @RainbowMango can you change npm run build to yarn run build ?

Done. The build settings are:
image

**Comment by RainbowMango** [comment]
Update: After changed `Base Directory` to `<Empty>`, the build for preview seems done. But the result seems can't reflect to GitHub, so,please push again?

**Comment by pigletfly** [comment]
It seems @docusaurus/core@2.0.0-beta.18 requires nodejs >=14.Can we choose nodejs version on netlify ? @RainbowMango

**Review by Arhell — COMMENTED** [review]
/lgtm

**Pull request merged**
