### PR TITLE
added ingress to interpret dependency

### LINKED ISSUE #439: Update Ingress to the default dependencinterpreter support list
**What would you like to be added**:

As https://github.com/karmada-io/karmada/pull/3885, we need to update the site: https://karmada.io/docs/next/userguide/globalview/customizing-resource-interpreter/#interpretdependency

**Why is this needed**:

/help

### PR DESCRIPTION
**Pull request by Shreya111111**
**What type of PR is this?**
Adding ingress to interpret dependency.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #439

**Special notes for your reviewer**:

I have added ingress to interpret dependency if there are any other changes or corrections then notify accordingly

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
@Shreya111111 Thanks, can you help make some changes to this file at the same time?
```
i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
```

**Comment by XiShanYongYe-Chang** [comment]
Please sign off refer to https://github.com/karmada-io/website/pull/447/checks?check_run_id=15703129699

**Comment by Shreya111111** [comment]
@XiShanYongYe-Chang can u plz tell if it is done correctly or not

**Comment by Shreya111111** [comment]
> 

yes

**Comment by XiShanYongYe-Chang** [comment]
In your pr, there are two commits included. The first commit is not signed. You can merge them into one commit and sign it.
```
git reset head~2
git add .
git commit -s -m "{commit message}"
git push origin shreya -f
```

**Comment by XiShanYongYe-Chang** [comment]
Hi, @Shreya111111 Have you encountered any difficulties? Let me try to help you.

**Comment by Shreya111111** [comment]
@XiShanYongYe-Chang  how many reviewers are needed to merge this PR 2 or 3 .

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
