### PR TITLE
[doc] sync override-policy.md from karmada

### PR DESCRIPTION
**Pull request by hanweisen**
Signed-off-by: hanweisen <hanweisen_yewu@cmss.chinamobile.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
The user guide of override-policy is missing. copy from karmada. I submit a PR https://github.com/karmada-io/karmada/pull/1896 move override-policy.md to userguide folder. If website will sync userguide from karmada with relsease 1.2. This PR should be closed.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by RainbowMango** [comment]
Wrong place? I can't see this from preview:
https://deploy-preview-66--karmada.netlify.app/

**Comment by hanweisen** [comment]
image
I can not find override-policy.md in this project

**Comment by hanweisen** [comment]
fixed https://deploy-preview-66--karmada.netlify.app/docs/next/

**Review by RainbowMango — APPROVED** [review]
/approve

Leave LGTM to @Arhell

**Comment by RainbowMango** [comment]
/lgtm

Thanks @hanweisen

**Pull request merged**
