### PR TITLE
add zoom plugin to docs

### PR DESCRIPTION
**Pull request by Arhell**
**What type of PR is this?**
/kind design
/kind documentation
/kind feature

**What this PR does / why we need it**:
for better usability documentation so that images can be enlarged

**Which issue(s) this PR fixes**:
resolve https://github.com/karmada-io/website/issues/108

### CODE REVIEW

**Review by rgrupesh — COMMENTED** [review]
Good work @Arhell.
/remove-lgtm

**Comment by Arhell** [comment]
> Good work @Arhell.
> 
> Can we do similar for homepage?

Ok I'll take a look

**Comment by Arhell** [comment]
сс  @RainbowMango

**Comment by RainbowMango** [comment]
Sorry @Arhell 
I can't clearly tell what the patch is and what's the difference between before and after.

Can you help give a more details description? Or, @rgrupesh can you?

**Comment by Arhell** [comment]
Or https://deploy-preview-110--karmada.netlify.app/docs/developers/guide/github-workflow

**Comment by rgrupesh** [comment]
> Sorry @Arhell I can't clearly tell what the patch is and what's the difference between before and after.
> 
> Can you help give a more details description? Or, @rgrupesh can you?

@RainbowMango So the patch/plugin basically adds zoom functionality to the pictures that we have on the site.

**Before patch:**
https://deploy-preview-107--karmada.netlify.app/docs/developers/guide/github-workflow
**After patch:**
https://deploy-preview-110--karmada.netlify.app/docs/developers/guide/github-workflow/

You should now be able to see the difference.

**Comment by RainbowMango** [comment]
Sorry, the pictures on my side can be zoomed in and out. 
So, I still can't tell the difference. By the way, I'm using Chrome.

**Comment by Arhell** [comment]
> Sorry, the pictures on my side can be zoomed in and out. So, I still can't tell the difference. By the way, I'm using Chrome.

I also use chrome
What do I have

not zoom
Screenshot_1

zoomed
Screenshot_2

**Comment by Poor12** [comment]
I have not seen the difference between them, too.

**Pull request closed without merging**
