### PR TITLE
update node version for netlify

### PR DESCRIPTION
**Pull request by Arhell**
**What type of PR is this?**
https://docusaurus.io/blog/releases/3.0#breaking-changes
/kind feature

### CODE REVIEW

**Comment by samzong** [comment]
/lgtm

this great!

**Review by samzong — APPROVED** [review]
/approve

**Review by Arhell — COMMENTED** [review]
cc @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
