### PR TITLE
add sidebar for v1.10 missed workload rebalancer doc

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

website of v1.10 should also have this doc, but now in v1.10 neither english version nor chinese version exist

so, add sidebar for v1.10 missed workload rebalancer doc.

**Which issue(s) this PR fixes**:

Fixes https://github.com/karmada-io/website/pull/639#issuecomment-2167306046

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by chaosi-zju** [comment]
@XiShanYongYe-Chang @zhzhuang-zju

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
