### PR TITLE
Add updating docs(v1.4-v1.5)

### PR DESCRIPTION
**Pull request by jwcesign**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add updating docs(v1.4-v1.5)

**Which issue(s) this PR fixes**:
Fixes #none

**Special notes for your reviewer**:
none

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
LGTM

**Comment by jwcesign** [comment]
I installed v1.4.2, and then followed the steps to upgrade to the master branch, all the e2e works fine.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
