### PR TITLE
add upgrade document for upgrading from 1.2 to 1.3

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Add upgrade document for upgrading from 1.2 to 1.3.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by RainbowMango** [comment]
Please resolve the conflicts.

**Comment by Poor12** [comment]
You need to edit `sidebar.js` to display the docs properly.

**Comment by XiShanYongYe-Chang** [comment]
> You need to edit `sidebar.js` to display the docs properly.

Thanks, updated.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
