### PR TITLE
remove lock files

### PR DESCRIPTION
**Pull request by Arhell**
**What type of PR is this?**

Add one of the following kinds:

/kind feature

**Which issue(s) this PR fixes**:
resolve https://github.com/karmada-io/website/issues/79

### CODE REVIEW

**Comment by Arhell** [comment]
I removed these files so that everything is on the server side
example taken from the official repository
https://github.com/facebook/docusaurus/tree/main/website

**Comment by RainbowMango** [comment]
> I removed these files so that everything is on the server side

Sorry I didn't get it. Why we don't need these files?

**Comment by Arhell** [comment]
> > I removed these files so that everything is on the server side
> 
> Sorry I didn't get it. Why we don't need these files?

not to worry about security, example
https://github.com/karmada-io/website/pull/78

I'll just update the entire dependencies in the json file

**Comment by RainbowMango** [comment]
I'm not worried about the securities, on the contrary, I think it's great to be able to identify potential security issues through these lock files.
My concern is if we removed the lock files, how do we find the potential security warnings?

> I'll just update the entire dependencies in the json file

What json file?

**Comment by Arhell** [comment]
> I'm not worried about the securities, on the contrary, I think it's great to be able to identify potential security issues through these lock files. My concern is if we removed the lock files, how do we find the potential security warnings?
> 
> > I'll just update the entire dependencies in the json file
> 
> What json file?

https://github.com/karmada-io/website/blob/main/package.json

In general, I argue that netlify does not need these files and for people who fork the site it was easier on different systems (Linux, Mac, Windows and others).

An example, as I wrote above, was taken from the official docusaurus repository

**Comment by RainbowMango** [comment]
cc @pigletfly for comment

**Comment by pigletfly** [comment]
It's better to have the lock files, at least the package-lock.json file.It's like go.mod go.sum file in Go world.If we modify the depends, add or remove them in package.json,then update them in package-lock.json.

**Comment by Arhell** [comment]
I remove yark lock file & update readme

**Review by rgrupesh — COMMENTED** [review]
/lgtm

**Pull request merged**
