### PR TITLE
多云案例文章修复排版内容.

### PR DESCRIPTION
**Pull request by yanggangtony**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
多云案例文章修复排版内容.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Poor12** [comment]
Great thanks.
/lgtm
/approve

**Comment by RainbowMango** [comment]
I wonder do we have similar issues on en docs?

**Comment by Poor12** [comment]
> I wonder do we have similar issues on en docs?

I have checked our en docs. No similar issues.

**Comment by RainbowMango** [comment]
OK. thanks.

**Pull request merged**
