### PR TITLE
enable clusterrole-aggregation controller

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind documentation
/kind feature

**What this PR does / why we need it**:

Refer to https://github.com/karmada-io/karmada/issues/3916

**Which issue(s) this PR fixes**:
Part of https://github.com/karmada-io/karmada/issues/3916

**Special notes for your reviewer**:

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
Just a reminder, this info should be included in upgrading documents.

**Comment by XiShanYongYe-Chang** [comment]
> Just a reminder, this info should be included in upgrading documents.

Thanks for reminding me. I have documented this point while tracking the issue.

**Pull request merged**
