### PR TITLE
nominate windsonsea to the global reviewers

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by RainbowMango** [comment]
/lgtm

@windsonsea has made a significant contribution, impressive!

**Comment by RainbowMango** [comment]
/approve

/hold
for @windsonsea confirm. (Feel free to unhold )

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by windsonsea** [comment]
wow, thanks, I would like to help you to review more about docs and text. 😄

**Pull request merged**
