### PR TITLE
Fix title header error

### PR DESCRIPTION
**Pull request by SAMZONG**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

By default, the header should be continuous.

**Which issue(s) this PR fixes**:
Fixes #

Fix title header error

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by windsonsea** [comment]
/lgtm

In a markdown file, headings should be hierarchical 1-2-3 and should not jump levels like 1-3-5.

**Comment by RainbowMango** [comment]
> In a markdown file, headings should be hierarchical 1-2-3 and should not jump levels like 1-3-5.

(Just a question) Why heading should be consecutive?  Do you know where can I find related documents?

I'm ok with this PR, but please also update the file under `i18n/zh`:
https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/concepts.md
By the way, for the style change, we don't need to sync to the previous version.

**Comment by windsonsea** [comment]
If you use [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) to check markdown syntax, the MD001 is talking about headings.

In VSCode Editor, you can also install an extension named `markdownlint`, which can provide many suggestions.

image

**Comment by RainbowMango** [comment]
> If you use [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) to check markdown syntax, the MD001 is talking about headings.

That's great! Good to know thanks. We didn't follow the practice before.

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by RainbowMango** [comment]
> I'm ok with this PR, but please also update the file under i18n/zh:
https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/concepts.md
By the way, for the style change, we don't need to sync to the previous version.

What do you think? @SAMZONG

**Comment by SAMZONG** [comment]
> 



> > I'm ok with this PR, but please also update the file under i18n/zh:
> > https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/concepts.md
> > By the way, for the style change, we don't need to sync to the previous version.
> 
> What do you think? @SAMZONG

Yes, we don't need update previous version.

This syntax issue, I was fixed in translate pr #383, But according to the principle of English first, we need to prioritize updating the English version.

**Comment by SAMZONG** [comment]
@RainbowMango @windsonsea 

I have completed all the modifications.

```
./docs/core-concepts/concepts.md
./versioned_docs/version-v1.6/core-concepts/concepts.md
./i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/concepts.md
./i18n/zh/docusaurus-plugin-content-docs/version-v1.6/core-concepts/concepts.md
```

update the markdown title hierarchy and synchronize it with v1.6 and the Chinese documentation.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
