### PR TITLE
Add security docs

### PR DESCRIPTION
**Pull request by Poor12**
Signed-off-by: Poor12 <shentiecheng@huawei.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add security docs

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
None

### CODE REVIEW

**Comment by RainbowMango** [comment]
Just assign it to me once it's ready.

**Comment by Poor12** [comment]
> Just assign it to me once it's ready.

Basiclly ready, need a email for reporting security vulnerabilities.

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by Poor12** [comment]
Move to community.

**Pull request closed without merging**
