### PR TITLE
add yarn.lock

### PR DESCRIPTION
**Pull request by samzong**
Signed-off-by: samzong.lu <samzong.lu@gmail.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Add yarn.lock for better support of users who use yarn.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
As for me, several .lock files are redundant
Example https://github.com/facebook/docusaurus
https://github.com/karmada-io/website/pull/82

**Comment by SAMZONG** [comment]
> As for me, several .lock files are redundant Example https://github.com/facebook/docusaurus #82

I noticed that we are using yarn for building in Netlify, so I think having a yarn.lock file is a good thing. 

https://app.netlify.com/sites/karmada/deploys/648d1e30e0b69b00081d5fdb

**Comment by RainbowMango** [comment]
We just removed `yarn.lock` file at #82, by @Arhell . 

> I noticed that we are using yarn for building in Netlify, so I think having a yarn.lock file is a good thing.

What's the benefits if we have the `yarn.lock` back?

**Comment by SAMZONG** [comment]
@RainbowMango

The package-lock.json is a lock file used by npm, while yarn.lock is the equivalent lock file used by Yarn. Both files serve essentially the same purpose, **BUT yarn does not recognize package-lock.json**. 

In general, it is sufficient to use one or the other; however, in our project we have situations where both are used, such as when the README.md instructs users to use npm, but Netlify built step uses Yarn. If the yarn.lock file is missing, there is no mechanism for locking dependencies for yarn users, and therefore I believe it is necessary to include it.

**Comment by SAMZONG** [comment]
> > In general, it is sufficient to use one or the other; however, in our project we have situations where both are used, such as when the README.md instructs users to use npm, but Netlify built step uses Yarn.
> 
> Thanks for the reminder, I didn't realize it before. I don't think we need two tools at the same time. So, can we update the README to use Yarn?

Okay, I'll update it at this PR.

**Pull request closed without merging**
