### PR TITLE
[zh] sync files in /upgrading

### PR DESCRIPTION
**Pull request by windsonsea**
/kind documentation

**What this PR does / why we need it**:
Added zh text to:
```
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v0.10-v1.0.md
```
**Special notes for your reviewer**:
/cc @Poor12

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/assign @Poor12

**Comment by Poor12** [comment]
Thanks. It seems that the contents of the upgraded documents are not long, would you like to translate the rest together?

**Comment by windsonsea** [comment]
> Thanks. It seems that the contents of the upgraded documents are not long, would you like to translate the rest together?

Done, the remained 3 files are synced too.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
