### PR TITLE
add zh metrics doc for recreate/update_resource_to_cluster

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

add zh metrics doc for recreate/update_resource_to_cluster

related PR: https://github.com/karmada-io/karmada/pull/5247

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

preview: [click](https://deploy-preview-665--karmada.netlify.app/zh/docs/next/reference/instrumentation/metrics/)

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
Could you only modify the target lines? Do not re-format all lines. It's hard to find which lines are really changed.

**Review by windsonsea — COMMENTED** [review]
/lgtm

**Comment by chaosi-zju** [comment]
cc @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
