### PR TITLE
Modify the multi-cluster Service discovery and multi-cluster ingress documents

### PR DESCRIPTION
**Pull request by Fish-pro**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Modify some problems in the document, while optimizing steps, the original library [karmada](https://github.com/karmada-io/karmada) has been merged, not synchronized to the library

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by rgrupesh — COMMENTED** [review]
/lgtm

**Comment by RainbowMango** [comment]
/assign @XiShanYongYe-Chang 
He will get back next week from a long vocation.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot.
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
