### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/karmada-io/website/issues/318

### CODE REVIEW

**Comment by Arhell** [comment]
@RainbowMango small dep update

**Comment by RainbowMango** [comment]
May I know why we need this?

**Comment by Arhell** [comment]
> May I know why we need this?

this is a small update as I wrote above + a small contribution from me. I make sure everything is up to date.

**Review by rgrupesh — COMMENTED** [review]
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
