### PR TITLE
JointCloud Logo Commit

### PR DESCRIPTION
**Pull request by jhnine**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
Add JointCloud Logo 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by RainbowMango** [comment]
Thanks @jhnine, please sign the commit according to 
https://github.com/karmada-io/website/pull/55/checks?check_run_id=6467027004

**Pull request merged**
