### PR TITLE
Fix indentations in en/zh glossary

### PR DESCRIPTION
**Pull request by windsonsea**
**What type of PR is this?**

/kind cleanup
/kind documentation

**What this PR does / why we need it**:

Fix bullets alignment, which shall indent 2 spaces for an unordered list.

### CODE REVIEW

**Comment by Poor12** [comment]
Is there any benefit to emptying two spaces? I feel similar.

**Comment by windsonsea** [comment]
Only an alignment optimization. It is more obvious if for an ordered list 1-2-3, all broken to be 1-1-1

image

**Review by RainbowMango — APPROVED** [review]
I like it!
/approve

Leave LGTM to @Poor12 for the final decision.

**Comment by Poor12** [comment]
Thanks.
/lgtm

**Pull request merged**
