### PR TITLE
built-in interpreter support statefulset

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

https://github.com/karmada-io/karmada/pull/3009

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Comment by XiShanYongYe-Chang** [comment]
/hold
Hi @chaunceyjiang, can you help update the file i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md at the same time.

**Comment by XiShanYongYe-Chang** [comment]
Thanks~
/lgtm
/hold-cancel

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
