### PR TITLE
put ZHEJIANG LAB to supporter list

### PR DESCRIPTION
**Pull request by weichenhao**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
Add zhejianglab Logo

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by RainbowMango** [comment]
Thanks!!!
/retile put ZHEJIANG LAB to supporter list

**Comment by RainbowMango** [comment]
/retitle put ZHEJIANG LAB to supporter list

**Comment by RainbowMango** [comment]
sorry, @weichenhao, I just want to help to amend the commit because we usually don't use Chinese in commit messages.

In order not to conflict with you. I'll stop.

**Comment by weichenhao** [comment]
Now，what's the problem?

**Comment by RainbowMango** [comment]
I guess you might need to squash your commits, and here is the guide:
https://karmada.io/docs/contributor/github-workflow#squash-commits

**Comment by RainbowMango** [comment]
By the way, GitHub can't recognize you by your email, you need to [add your email to GitHub](https://github.com/settings/emails), otherwise GitHub can't count your contributions.

**Pull request closed without merging**
