### PR TITLE
Add karmadactl addons subcommand docs

### PR DESCRIPTION
**Pull request by ONE7live**
Signed-off-by: ONE7live <wangqi_yewu@cmss.chinamobile.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add karmadactl addons subcommand docs, refer to [karmada-io/karmada#2134](https://github.com/karmada-io/karmada/pull/2134)

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by RainbowMango** [comment]
Thanks @ONE7live for doing this. 

I'm thinking if we need a separate document for `karmadactl` functionality.  
@lonelyCZ Any suggestions?

**Comment by lonelyCZ** [comment]
> I'm thinking if we need a separate document for karmadactl functionality.

Yes, there could be an exclusive catalogue for `karmadactl` to describe the necessary subcommands(not only `options` but also usage example).

**Comment by ONE7live** [comment]
@RainbowMango @lonelyCZ Can we give an example first? Then resolve it with a new Issue and PR. Because in my opinion, the complete karmadactl function documentation needs enough time to write, during which we still need to explain some functions (such as addons)，what do y'all think?

**Comment by lonelyCZ** [comment]
> Because in my opinion, the complete karmadactl function documentation needs enough time to write, during which we still need to explain some functions (such as addons)，what do y'all think?

Don't need complete doc. We can add it one by one. Like 
image

cc @RainbowMango

**Comment by Poor12** [comment]
Maybe we can refer to https://kubernetes.io/docs/reference/kubectl/ about kubectl. We need a command guide for every subcommand and options(it's more like a generated thing). Also we need to provide some usage conventions about how to use it.

**Comment by RainbowMango** [comment]
Yeah, I agree with @Poor12. CLI not used only by administrators.

So, please @Poor12 help to set up the initial page and make a room for `addons`.

**Comment by lonelyCZ** [comment]
> Maybe we can refer to https://kubernetes.io/docs/reference/kubectl/ about kubectl. We need a command guide for every subcommand and options(it's more like a generated thing). 

https://github.com/karmada-io/karmada/pull/2260 planed to import it, but we were going to import it when the cli more stable, what do you think?

**Comment by RainbowMango** [comment]
Thanks for reminding me. That's the approach to automatically generate the docs, not sure if we can customize the doc a little bit such as adding more examples.

I'll look at it later.

**Comment by Poor12** [comment]
#176 move karmadactl manual to reference. Guess it's time to complete the karmadactl guide. I created three files to store karmadactl's options, subcommands and best practices.

**Comment by ONE7live** [comment]
Great, I'll resubmit a PR to refine it

**Pull request closed without merging**
