### PR TITLE
make doc prettier in performance-test-setup-for-karmada.md

### PR DESCRIPTION
**Pull request by windsonsea**
/kind documentation

This is a try to make the doc prettier. Performed two actions:

1. Run `npx prettier --w` to automatically remove blank lines, fix spaces, and fix code symbol like line 350
2. Tweak long lines to enable easily review changes that may occur later

### CODE REVIEW

**Comment by Poor12** [comment]
BTW, can `npx prettier --w` join our CI check?

**Comment by windsonsea** [comment]
`Prettier` can change all content to a standard markdown format and check some syntax of code, but sometimes it may break the link url. In this case, a manual check is required. 

Refer to the official docs: https://prettier.io/docs/en/install.html

**Comment by Poor12** [comment]
In my opinion, it is more like an auxiliary tool. You can use it as an aid when writing markdown. But it is not necessary to scan all documents. If you'd like,  I suggest adding an optional chapter in https://karmada.io/docs/next/contributor/contribute-docs.

**Comment by windsonsea** [comment]
This can be closed according to the comments above.

**Pull request closed without merging**
