### PR TITLE
refactor css

### PR DESCRIPTION
**Pull request by Arhell**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
transfer of styles to 1-n file for easier navigation and development

**Which issue(s) this PR fixes**:
resolve https://github.com/karmada-io/website/issues/94

### CODE REVIEW

**Comment by RainbowMango** [comment]
@rgrupesh Could you please help with it?

**Comment by Arhell** [comment]
> @Arhell What do you mean exactly by 1-n? Are we putting all css in one file `custom.css`?

Yes

**Review by rgrupesh — COMMENTED** [review]
/lgtm

**Comment by Arhell** [comment]
сс  @RainbowMango

**Pull request closed without merging**
