### PR TITLE
Add KubeCon talks of trip

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Add talks at KubeCon China 2023.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
Could we add only the KubeCon line and leave everything else unchanged?

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by RainbowMango** [comment]
@windsonsea I wish I could. But the IDE (I'm using Goland and WebStorm) always tells me to format the table, I hate to touch those unrelated lines too...

**Comment by windsonsea** [comment]
lol, lgtm

**Pull request merged**
