### PR TITLE
Nominate Poor12 and Tingtal as docs owners

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR nominates @Poor12 and @Tingtal onto the owner list, they have been contributing a lot recently. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Poor12** [comment]
Thanks~
/lgtm

**Review by rgrupesh — COMMENTED** [review]
Thank you for the contribution.

/lgtm

**Comment by windsonsea** [comment]
Congratulations! 🎁 🎆

**Comment by Tingtal** [comment]
Cheers to you all :bowtie:

**Review by Arhell — COMMENTED** [review]
/lgtm

**Pull request merged**
