### PR TITLE
update Supporters list

### PR DESCRIPTION
**Pull request by Arhell**
**What type of PR is this?**

/kind design

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/website/issues/326

After fix 

Screenshot_1

### CODE REVIEW

**Comment by Arhell** [comment]
cc @RainbowMango

**Comment by Arhell** [comment]
@rgrupesh

**Review by rgrupesh — COMMENTED** [review]
Center align looks good.

/lgtm

**Comment by RainbowMango** [comment]
I can see the newly added logo is smaller than the others but seems no difference after this patch.

I'm using Chrome 110.0.5481.178, windows from the [deploy-preview](https://deploy-preview-327--karmada.netlify.app/).

**Comment by Poor12** [comment]
> I can see the newly added logo is smaller than the others but seems no difference after this patch.
> 
> I'm using Chrome 110.0.5481.178, windows from the [deploy-preview](https://deploy-preview-327--karmada.netlify.app/).

It differs in dark mode.

**Comment by RainbowMango** [comment]
Thanks for reminding me. This logo has a white background. 

@whitewindmills Do you have a logo in PNG format but no white background? Just like the others?

**Comment by RainbowMango** [comment]
@Arhell Could you please rebase this PR? We just updated the image in #329 .

**Comment by RainbowMango** [comment]
Why the CECloud logo looks still smaller than others?

**Comment by Arhell** [comment]
> Why the CECloud logo looks still smaller than others?

in width it is the same as all the others, the height here does not need to be corrected because it will be stretched.
But in general, there is such a picture.

**Review by Arhell — COMMENTED** [review]
@RainbowMango please take a look, this PR fixes the display of logos on a dark theme
an example as it is here https://github.com/karmada-io/website/issues/326

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
