### PR TITLE
Update ResourceBinding label to annotation

### PR DESCRIPTION
**Pull request by mathlsj**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Work marks resourcebinding on annotation not label

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Thanks~
/lgtm

**Review by XiShanYongYe-Chang — COMMENTED** [review]
We have added some other labels or annotations on the resource, can you help find it and add it in the next pr?

Such as:

https://github.com/karmada-io/karmada/blob/master/pkg/util/constants.go#L26-L27

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by mathlsj** [comment]
> We have added some other labels or annotations on the resource, can you help find it and add it in the next pr?
> 
> Such as:
> 
> https://github.com/karmada-io/karmada/blob/master/pkg/util/constants.go#L26-L27

OK

**Pull request merged**
