### PR TITLE
update docs of customizing resource interpreter for declarative

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind feature
/kind documentation

**What this PR does / why we need it**:

Update doc of `customizing-resource-interpreter.md` for declarative configuration.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
```
update docs of customizing resource interpreter for declarative
```

### CODE REVIEW

**Comment by Poor12** [comment]
https://github.com/karmada-io/karmada/tree/master/examples/karmadactlinterpret  broken link

**Comment by XiShanYongYe-Chang** [comment]
> https://github.com/karmada-io/karmada/tree/master/examples/karmadactlinterpret broken link

Yes, I'm going to submit a corresponding PR on the karmada library to express this example.

**Comment by XiShanYongYe-Chang** [comment]
Need to wait for https://github.com/karmada-io/karmada/pull/2886 to merge.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
