### PR TITLE
Supplement missing colon.

### PR DESCRIPTION
**Pull request by Zhuzhenghao**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In the section of the override rules, two colons are missing

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
Seems you might have to sign the DCO.

**Comment by Zhuzhenghao** [comment]
okay

**Review by Arhell — COMMENTED** [review]
/lgtm

**Pull request merged**
