### PR TITLE
update Supporters block

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/karmada-io/website/issues/39

### CODE REVIEW

**Comment by Arhell** [comment]
/assign @RainbowMango
I updated the block but didn't find 2 logos

**Comment by RainbowMango** [comment]
You can find all the logos from git history. E.g. You can get it from https://github.com/RainbowMango/website-3/tree/main/static/img.

This patch looks good! Thanks. 
By the way, I'm in a holiday and get back to the office at Thursday. Before that maybe slow response.

**Comment by Arhell** [comment]
> You can find all the logos from git history. E.g. You can get it from https://github.com/RainbowMango/website-3/tree/main/static/img.
> 
> This patch looks good! Thanks. By the way, I'm in a holiday and get back to the office at Thursday. Before that maybe slow response.

Done thank you

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
