### PR TITLE
Update troubleshooting.md

### PR DESCRIPTION
**Pull request by chaunceyjiang**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/2571

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please push commit wish DCO
https://github.com/karmada-io/website/pull/182/checks?check_run_id=8513213225

**Comment by Poor12** [comment]
Hi @chaunceyjiang, could you please sign the DCO so we can move this pr on :)

**Comment by chaunceyjiang** [comment]
Oh, sorry. I forgot.

> Hi @chaunceyjiang, could you please sign the DCO so we can move this pr on :)

@Poor12 Done.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
