### PR TITLE
[zh] Sync core-concepts/components.md

### PR DESCRIPTION
**Pull request by diebbCN**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Sync with the english text

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
/lgtm

These changes are to keep consistent with english version. You need to sign off by running:

```
git commit -s --amend
git push -f
```

**Comment by diebbCN** [comment]
> /lgtm
> 
> These changes are to keep consistent with english version. You need to sign off by running:
> 
> ```
> git commit -s --amend
> git push -f
> ```
@windsonsea I got it.

**Comment by diebbCN** [comment]
> /lgtm
> 
> These changes are to keep consistent with english version. You need to sign off by running:
> 
> ```
> git commit -s --amend
> git push -f
> ```

Sorry, I'm new to Git. What should I do next? Should I resubmit a PR? @windsonsea

**Comment by windsonsea** [comment]
1. Run this command on your `patch-1` branch locally:

   ```git
   git commit -s --amend
   ```
1. Need not change nothing. Press the ESC key, and type `:wq` 

1. Run the command to push again:

   ```
   git push origin patch-1 -f
   ```

**Comment by diebbCN** [comment]
> 1. Run this command on your `patch-1` branch locally:
>    ```
>    git commit -s --amend
>    ```
> 2. Need not change nothing. Press the ESC key, and type `:wq`
> 3. Run the command to push again:
>    ```
>    git push origin patch-1 -f
>    ```

Thank you, I understand how to do it now :) @windsonsea

**Review by windsonsea — COMMENTED** [review]
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve
Thanks.

**Pull request merged**
