### PR TITLE
replace Button to components

### PR DESCRIPTION
**Pull request by Arhell**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
components must be in their own folder

**Which issue(s) this PR fixes**:
resolve https://github.com/karmada-io/website/issues/100

### CODE REVIEW

**Comment by Arhell** [comment]
/assign @RainbowMango
small refactor

**Comment by RainbowMango** [comment]
Hi @Arhell I can't tell what's changed, can you give a more detailed description?

> components must be in their own folder

**Comment by Arhell** [comment]
> Hi @Arhell I can't tell what's changed, can you give a more detailed description?
> 
> > components must be in their own folder
> 
> I don't know what that means.

I moved it to a separate folder, an example of how these components https://github.com/karmada-io/website/tree/main/src/components

**Pull request merged**
