### PR TITLE
fix github icon on dark theme

### PR DESCRIPTION
**Pull request by Arhell**
**What type of PR is this?**
fix bug

/kind bug

**Which issue(s) this PR fixes**:
resolve https://github.com/karmada-io/website/issues/70

### CODE REVIEW

**Review by rgrupesh — CHANGES_REQUESTED** [review]
This looks good. Can we do similar for `karmada icon` on the header?

**Comment by Arhell** [comment]
> This looks good. Can we do similar for `karmada icon` on the header?

next PR

**Review by rgrupesh — APPROVED** [review]

**Comment by RainbowMango** [comment]
/approve

Thanks.

**Pull request merged**
