### PR TITLE
Add ClusterEviction plugin

### PR DESCRIPTION
**Pull request by seanlaii**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add ClusterEviction plugin description in `Developer Guide/Customize the scheduler` page.

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/4803

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Related https://github.com/karmada-io/karmada/issues/4803

**Comment by XiShanYongYe-Chang** [comment]
Hi @seanlaii, thanks for your contribution!
Please sign off refer to https://github.com/karmada-io/website/pull/588/checks?check_run_id=23640836626

**Comment by seanlaii** [comment]
> Hi @seanlaii, thanks for your contribution! Please sign off refer to https://github.com/karmada-io/website/pull/588/checks?check_run_id=23640836626

Thanks for the info! Added.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
LGTM

**Review by RainbowMango — APPROVED** [review]
/approve

**Review by Vacant2333 — APPROVED** [review]
/approve thanks

**Pull request merged**
