### PR TITLE
adds karmadactl flags for proper display

### PR DESCRIPTION
**Pull request by LavredisG**
/kind documentation

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/5915

### CODE REVIEW

**Comment by LavredisG** [comment]
A bit unrelated to the specific PR, but since it's on this page:

What is the purpose of the metrics-adapter? I would suppose that it is needed in order to expose <a href=https://karmada.io/docs/reference/instrumentation/metrics>Karmada metrics</a>, but I can't curl the :8080 port of the pod running the metrics server. However, I can scrape for example the karmada-controller pod to get metrics related to the controller instead.

In addition to that, what is the purpose of the metrics-server? I can scrape karmada-controller for example even without them being installed on the member clusters and get info about each member cluster that has joined karmada.

Concluding, what is the purpose of the metrics-adapter and metrics-server pods?

**Comment by RainbowMango** [comment]
cc @zhzhuang-zju Can you help to take a look?

**Comment by zhzhuang-zju** [comment]
thanks @LavredisG 
/assign

**Comment by zhzhuang-zju** [comment]
/lgtm
assign @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by RainbowMango** [comment]
@zhzhuang-zju Can you help to open another PR to sync the zh docs?

**Comment by RainbowMango** [comment]
> Concluding, what is the purpose of the metrics-adapter and metrics-server pods?

@LavredisG 
The `metrics-server` running on member clusters, is used to expose metrics of Kubernetes so that Karmada can grab metrics from it.
The `karmada-metrics-adapter` is used to collect metrics of Kubernetes, and then aggregate the metrics for global HPA purposes.

**Comment by LavredisG** [comment]
> > Concluding, what is the purpose of the metrics-adapter and metrics-server pods?
> 
> @LavredisG The `metrics-server` running on member clusters, is used to expose metrics of Kubernetes so that Karmada can grab metrics from it. The `karmada-metrics-adapter` is used to collect metrics of Kubernetes, and then aggregate the metrics for global HPA purposes.

Thank you! In that case, in order to get metrics from the page of "Karmada Metrics Reference" do I have to scrape each target mentioned there that exports the metrics I need?

**Pull request merged**
