### PR TITLE
updaete override-policy fieldSelector

### PR DESCRIPTION
**Pull request by fengshunli**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by RainbowMango** [comment]
Generally looks good, please update the following pages as well:
- current cn version: https://github.com/karmada-io/website/blob/main/docs/userguide/scheduling/override-policy.md

Given that you are Chinese, can you help update the localized pages as well? that are:
- release 1.4 version: https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/override-policy.md
- current version: https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/scheduling/override-policy.md

**Comment by fengshunli** [comment]
dong @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Thanks for your quick response.

**Comment by fengshunli** [comment]
Can you add OWNERS of reviewers to me? @RainbowMango

**Comment by RainbowMango** [comment]
We appreciated all your contributions to this project. 
Please go through the [requirements](https://github.com/karmada-io/community/blob/main/community-membership.md#requirements-1). There are some eligibility rules, and you can self-nominate once you are qualified.

**Pull request merged**
