### PR TITLE
fix items on tablet & mobile

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/karmada-io/website/issues/28

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
Hi @Arhell ,

We've decided to use https://docusaurus.io/ to refactor the website, and @pigletfly will help to do it. 
I don't want to waste your effort, so I guess you should know it. 

I appreciated your contribution.

**Comment by Arhell** [comment]
> Hi @Arhell ,
> 
> We've decided to use https://docusaurus.io/ to refactor the website, and @pigletfly will help to do it. I don't want to waste your effort, so I guess you should know it.
> 
> I appreciated your contribution.

Hello, no problem, I'm making minor corrections.

+ I looked, I think it's better to use the 2nd version.

I would like to support it for the needs of the community

**Comment by RainbowMango** [comment]
> I would like to support it for the needs of the community

Thanks. If you are interested in contributing to this community, I'd like to sponsor you as the owner of the website project.

By the way, have you received the invitation of becoming a member of the Karmada organization?

**Pull request merged**
