### PR TITLE
Add AIML INSTITUTE logo to supporters

### PR DESCRIPTION
**Pull request by algebra2k**
Signed-off-by: algebra2k <jackson.cloudnative@gmail.com>

### CODE REVIEW

**Comment by algebra2k** [comment]
cc @RainbowMango

**Comment by RainbowMango** [comment]
Thanks for your support! 

By the way, what's the full name of your company in English?

**Comment by algebra2k** [comment]
> Thanks for your support!
> 
> By the way, what's the full name of your company in English?

Thank you very much, the English name of our company is AIML Institute (Nanjing) Co. Ltd

**Pull request merged**
