### PR TITLE
update doc of built-in Interpreter

### PR DESCRIPTION
**Pull request by neteric**
add pod to Built-in InterpretHealth Interpreter

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Poor12** [comment]
Generally looks good, please update the following pages as well:

- current cn version: https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md

**Comment by neteric** [comment]
> Generally looks good, please update the following pages as well:
> 
> * current cn version: https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md

Done
/cc @Poor12

**Review by RainbowMango — APPROVED** [review]
/approve
Thanks.

**Pull request merged**
