### PR TITLE
Add more spaces above Why Karmada

### PR DESCRIPTION
**Pull request by Arhell**
**What type of PR is this?**
fix ui

/kind feature

**Which issue(s) this PR fixes**:
resolve https://github.com/karmada-io/website/issues/62

### CODE REVIEW

**Comment by RainbowMango** [comment]
Generally looks good to me.

Just a question, do you think it'd be better to use the same font size for 
- What is Karmada
- Why Karmada
- How It Works ?

Now I see `Why Karmada` and `How it works` is smaller than `What is Karmada`.

**Comment by Arhell** [comment]
> Generally looks good to me.
> 
> Just a question, do you think it'd be better to use the same font size for
> 
> * What is Karmada
> * Why Karmada
> * How It Works ?
> 
> Now I see `Why Karmada` and `How it works` is smaller than `What is Karmada`.

I think yes, but that's in another PR.

**Comment by RainbowMango** [comment]
> I think yes, but that's in another PR.

That makes sense to me.
/lgtm
/approve

Thanks.

**Pull request merged**
