### PR TITLE
Add prometheus config for karmada-controller-manager

### PR DESCRIPTION
**Pull request by Poor12**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add prometheus config for karmada-controller-manager

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
None

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
