### PR TITLE
How it works rescaled

### PR DESCRIPTION
**Pull request by rgrupesh**
It rescales `how it works` image.

### Screenshot

<details>
  <summary>Before</summary>

before1

</details>

<details>
  <summary>After</summary>

after1

</details>

Signed-off-by: Rupesh Gelal <rupeshgelal9@gmail.com>

### CODE REVIEW

**Comment by rgrupesh** [comment]
> Can you help describe what this PR solves? Yeah, more descriptions for other guys, then they might help to review it.

Description added.

**Comment by RainbowMango** [comment]
I'm curious why it looks fine in the preview? https://deploy-preview-47--karmada.netlify.app/

**Comment by RainbowMango** [comment]
No, The preview website is built based on each PR, not the main branch.
I think this issue was introduced by #46. See https://deploy-preview-46--karmada.netlify.app/.

**Review by Arhell — COMMENTED** [review]
/lgtm

**Pull request merged**
