### PR TITLE
doc: format command line prompts

### PR DESCRIPTION
**Pull request by B1F030**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Format command line prompts:
If the code block contains only commands, remove the command line prompt `$`/`#`;
If the code block contains commands and output logs, keep the command line prompt `$`;
When the code block is `shell`/`sh`/`bash`, use `$` instead of `#`, because `#` may be performed as comment in website.

**Which issue(s) this PR fixes**:
related [comment](https://github.com/karmada-io/website/pull/603#discussion_r1604534517)

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
/lgtm thanks for your import commit!

> Format command line prompts:
If the code block contains only commands, remove the command line prompt $/#;
If the code block contains commands and output logs, keep the command line prompt $;
When the code block is shell/sh/bash, use $ instead of #, because # may be performed as comment in website.

I think new documents added in the future need to follow these rules as well, and be formatted as uniformly as possible

**Review by windsonsea — COMMENTED** [review]
/lgtm
Thanks.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
