### PR TITLE
change error from NotFound to MethodNotSupported

### PR DESCRIPTION
**Pull request by ikaven1024**
Signed-off-by: yingjinhui <yingjinhui@didiglobal.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ikaven1024** [comment]
cc @XiShanYongYe-Chang

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm
/cc @RainbowMango

**Comment by XiShanYongYe-Chang** [comment]
Related with https://github.com/karmada-io/karmada/pull/2413

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
