### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by calvin-puram**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
  Fix some typos
**Which issue(s) this PR fixes**:
  Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by RainbowMango** [comment]
Hi @calvin-puram Thanks for doing this. I guess this is done by some tools, right? Can you share which tools you are using?

**Review by RainbowMango — COMMENTED** [review]
/lgtm

Would you mind handling the DCO thing? You can sign your commit as per this guide:
https://github.com/karmada-io/website/pull/416/checks?check_run_id=14904219544

**Comment by calvin-puram** [comment]
> Hi @calvin-puram Thanks for doing this. I guess this is done by some tools, right? Can you share which tools you are using?

@RainbowMango Yeah I used [Grammarly](https://www.grammarly.com/)

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
Thanks.

**Pull request merged**
