### PR TITLE
Add release docs

### PR DESCRIPTION
**Pull request by Poor12**
Signed-off-by: Poor12 <shentiecheng@huawei.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add release docs

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
None

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/lgtm

cc @kevin-wangzefeng

**Comment by Poor12** [comment]
/hold
Need to add release artifacts and container address.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
