### PR TITLE
refactor Why Karmada list

### PR DESCRIPTION
**Pull request by Arhell**
**What type of PR is this?**

Add one of the following kinds:

/kind cleanup
/kind feature

**What this PR does / why we need it**:
refactor

**Which issue(s) this PR fixes**:
resolve https://github.com/karmada-io/website/issues/69

### CODE REVIEW

**Comment by RainbowMango** [comment]
@Arhell Can you explain why we need this?

**Comment by Arhell** [comment]
> @Arhell Can you explain why we need this?

yes, I removed unnecessary divs, moved the data to the right folder (example with supporters), so it will be easier to support it in the future, data in 1st place, code in another.

**Review by rgrupesh — COMMENTED** [review]
Imo, looks more organized now.

**Comment by RainbowMango** [comment]
/approve

Thanks.

**Pull request merged**
